In [1]:
import numpy as np
import pandas as pd

In [6]:
#Q1.Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


arr = np.array([1,2,3,4,5])
print(arr)
arr.dtype

[1 2 3 4 5]


dtype('int32')

In [8]:
#Q2. Given a NumPy array 'arr', check if its data type is float64.
#       arr = np.array([1.5, 2.6, 3.7])



arr = np.array([1.5, 2.6, 3.7])
arr.dtype

dtype('float64')

In [10]:
#Q3.  Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr = np.array([1+2j,2+3j,3+4j])
print(arr)
arr.dtype

[1.+2.j 2.+3.j 3.+4.j]


dtype('complex128')

In [16]:
#Q4. Convert an existing NumPy array 'arr' of integers to float32 data type.

arr = np.array([1,2,3,4,5])
arr1 = arr.astype(np.float32)
print(arr1)
arr1.dtype


[1. 2. 3. 4. 5.]


dtype('float32')

In [19]:
#Q5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

arr = np.array([1.5, 2.6, 3.7])
print(arr)
print(arr.dtype)


arr1 = arr.astype(np.float32)
arr1.dtype

[1.5 2.6 3.7]
float64


dtype('float32')

In [3]:
#Q6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data 
# type.

def array(a):
    print(a.size)
    print(a.shape)
    print(a.dtype)


arr = np.array([1,2,3,4,5])
array(arr)
arr1 = np.array([[1.1,2,3.3,4],[5.5,6,7.7,8]])
array(arr1)

5
(5,)
int32
8
(2, 4)
float64


In [3]:
# Q7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.


def array_dimension(a):
    return a.ndim



arr = np.array([1,2,3,4,5])
array_dimension(arr)




1

In [8]:
#Q8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total 
#           size in bytes.


def item_size(a):
    item_size = a.itemsize
    total_size = a.nbytes
    return item_size, total_size


a = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size(a)
print(f"item size {item_size}")
print(f"total size {total_size}")






item size 4
total size 24


In [13]:
#Q9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.




def array_strides(a):
    return a.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)
print(f"Array strides: {strides}")







Array strides: (12, 4)


In [15]:
#Q10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape 
#    and strides of the array.


def shape_stride_relationship(a):
    shape = a.shape
    strides = a.strides
    print(f"shape:{shape} & strides:{strides}")
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape_stride_relationship(arr)
    





shape:(2, 3) & strides:(12, 4)


In [16]:
#Q11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of 
#    zeros with `n` elements.


def create_zeros_array(n):
    return np.zeros(n)
a = int(input("enter a integer number : "))
create_zeros_array(a)




enter a integer number : 10


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
#Q12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
#      NumPy array filled with ones of size `rows x cols`.


def create_ones_matrix(x,y):
    return np.ones((x,y))
rows = int(input("enter a integer row number : "))
cols = int(input("enter a integer colum number : "))
create_ones_matrix(rows,cols)
    

enter a integer row number : 10
enter a integer colum number : 10


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
#Q13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
#     creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 
#      `step`.

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)
start = int(input("enter the start value : "))
stop = int(input("enter the stop value : "))
step = int(input("enter the step value : "))
generate_range_array(start, stop, step)

    
    




enter the start value : 1
enter the stop value : 20
enter the step value : 3


array([ 1,  4,  7, 10, 13, 16, 19])

In [25]:
 #Q14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
#      arguments and generates a NumPy array with num equally spaced values between `start` and `stop` 
#      (inclusive).


def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)
start = int(input("enter the start value : "))
stop = int(input("enter the stop value : "))
num = int(input("enter the num value : "))
generate_linear_space(start,stop,num)

enter the start value : 4
enter the stop value : 62
enter the num value : 9


array([ 4.  , 11.25, 18.5 , 25.75, 33.  , 40.25, 47.5 , 54.75, 62.  ])

In [3]:
#Q15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
#     identity matrix of size `n x n` using `numpy.eye`.


def create_identity_matrix(n):
    return np.eye(n)

n= int(input("enter a value : "))
create_identity_matrix(n)



enter a value : 4


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
#Q16.Write a function that takes a Python list and converts it into a NumPy array.

def list_to_array(l):
    return np.array(l)

list=[1,2,3,4,5,6,7,8,9]
list_to_array(list)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#Q17.Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the 
#      same data.


arr = np.array([1,2,3,4,5])
print(arr)
arr1 = arr.view()
print("view array: ",arr1)

arr1[1] = 10
print("view array after modifi: ",arr1)
print("array after modifi the view array: ",arr)

[1 2 3 4 5]
view array:  [1 2 3 4 5]
view array after modifi:  [ 1 10  3  4  5]
array after modifi the view array:  [ 1 10  3  4  5]


In [9]:
#Q18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.


def concatenate_array(a1, a2, ax):
    return np.concatenate((a1, a2), axis=ax)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
axis = int(input(" choose 0(row) or 1(colum)  for concatenate the arrays: "))
concatenate_array(arr1, arr2, axis)
    

 choose 0(row) or 1(colum)  for concatenate the arrays: 1


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [10]:
def concatenate_array(a1, a2, ax):
    return np.concatenate((a1, a2), axis=ax)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
axis = int(input(" choose 0(row) or 1(colum)  for concatenate the arrays: "))
concatenate_array(arr1, arr2, axis)
    

 choose 0(row) or 1(colum)  for concatenate the arrays: 0


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [17]:
#Q19.Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
#     concatenate`.

arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([[7], [8], [9]])
print("array 1:\n",arr1)

print("array 2:\n",arr2)

arr3 = np.concatenate((arr1, arr2), axis=1)
print("concatenate array:\n",arr3)

array 1:
 [[1 2]
 [3 4]
 [5 6]]
array 2:
 [[7]
 [8]
 [9]]
concatenate array:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [3]:
#Q20. Write a function that vertically stacks multiple NumPy arrays given as a list.

def vertically_stacks(array):
     return np.vstack(array)
    
arr = [np.array([1, 2, 3]), np.array([4, 5, 6]), np.array([7, 8, 9])]
vertically_stacks(arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#Q21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) 
#      with a given step size.


def creat_array(start,end,step):
    return np.arange(start,end+1,step)

start = int(input("Enter the start value: "))
end = int(input("enter the end value: "))
step = int(input("enter the step value: "))
creat_array(start,end+1,step)

Enter the start value: 1
enter the end value: 20
enter the step value: 2


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [3]:
#Q 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1

def array_equally_spaced():
    return np.linspace(0,1,10)

array_equally_spaced()

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [4]:
#Q23.  Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 
#         1000 (inclusive).



def log_spaced_array():
    return np.logspace(0, 3, 5)
log_spaced_array()



array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

In [5]:
#Q24.  Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values 
#       are random integers between 1 and 100.


array = np.random.randint(1, 101, size=(5, 3))

df = pd.DataFrame(array, columns=['Column1', 'Column2', 'Column3'])

print(df)


   Column1  Column2  Column3
0       65       39       58
1       96       69       88
2       89       89       20
3       43       67       46
4       41       67        2


In [11]:
#Q25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
#     with zeros. Use NumPy operations within the Pandas DataFrame.


def negative_to_zerro(df,column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df
data = {
    'A': [1, -2, 3, -4, 5],
    'B': [-1, 2, -3, 4, -5],
    'C': [10, -20, 30, -40, 50]
}
df = pd.DataFrame(data)

print("Original DataFrame: \n",df)
df = negative_to_zerro(df,'C')
print("DataFrame after replacing negatives in column 'B': \n",df)

Original DataFrame: 
    A  B   C
0  1 -1  10
1 -2  2 -20
2  3 -3  30
3 -4  4 -40
4  5 -5  50
DataFrame after replacing negatives in column 'B': 
    A  B   C
0  1 -1  10
1 -2  2   0
2  3 -3  30
3 -4  4   0
4  5 -5  50


In [12]:
#Q26. Access the 3rd element from the given NumPy array.
#      arr = np.array([10, 20, 30, 40, 50])



arr = np.array([10, 20, 30, 40, 50])

third_element = arr[2]
print(third_element)

30


In [13]:
#Q27. Retrieve the element at index (1, 2) from the 2D NumPy array.
#       arr_2d = np.array([[1, 2, 3],
#                          [4, 5, 6],
#                          [7, 8, 9]])

arr_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
    
arr_2d[1,2]

6

In [2]:
#Q28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
#           arr = np.array([3, 8, 2, 10, 5, 7])


arr = np.array([3, 8, 2, 10, 5, 7])
ARR =arr>5
result = arr[ARR]
result
    


array([ 8, 10,  7])

In [3]:
#Q29.  Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
#          arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])



arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

In [9]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
#             arr_2d = np.array([[1, 2, 3],
#                                [4, 5, 6],
#                                [7, 8, 9]])


arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

    
sub_array = arr_2d[0:2, 1:3]
print(sub_array)



[[2 3]
 [5 6]]


In [2]:
#31.  Write a NumPy function to extract elements in specific order from a given 2D array based on indices 
#        provided in another array.



def extract_elements(arr, indices):
   
    extracted_elements = np.empty(indices.shape, dtype=arr.dtype)
    
    
    for i in range(indices.shape[0]):
        for j in range(indices.shape[1]):
            row, col = indices[i, j]
            extracted_elements[i, j] = arr[row, col]
    
    return extracted_elements


arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

indices = np.array([
    [(0, 0), (1, 1)],
    [(2, 2), (0, 2)]
])

extracted = extract_elements(arr, indices)
print(extracted)


[[[1 1]
  [5 5]]

 [[9 9]
  [3 3]]]


In [7]:
#Q32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using 
#      boolean indexing.


def filters_elements_greater(arr,threshold):
    elements = arr[arr > threshold]
    return elements

arr = np.array([1,2,3,4,5,6,7,8,9])
threshold = 4
filters_elements_greater(arr,threshold)

array([5, 6, 7, 8, 9])

In [9]:
#Q33.  Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three 
#      separate arrays for each dimension.

def extract_elements_3d(arr, x_indices, y_indices, z_indices):
    if not (x_indices.shape == y_indices.shape == z_indices.shape):
        raise ValueError("Index arrays must have the same shape")
    extracted_elements = arr[x_indices, y_indices, z_indices]
    return extracted_elements   



arr = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])
    
    

x_indices = np.array([0, 1, 2])
y_indices = np.array([1, 0, 2])
z_indices = np.array([2, 1, 0])


extract_elements_3d(arr, x_indices, y_indices, z_indices)


array([ 6, 11, 25])

In [2]:
#Q34. Write a NumPy function that returns elements from an array where both two conditions are satisfied 
#     using boolean indexing.




def get_elements(arr, condition1, condition2):
  
    return arr[condition1 & condition2]


arr = np.array([1, 2, 3, 4, 5, 6])
condition1 = arr > 2
condition2 = arr < 5
result = get_elements(arr, condition1, condition2)
print(result)


[3 4]


In [3]:
#Q35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided 
#     in separate arrays.




def extract_elements(arr, row_indices, col_indices):
    
    return arr[row_indices, col_indices]


arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])

result = extract_elements(arr, row_indices, col_indices)
print(result) 


[3 5 7]


In [4]:
#Q36.  Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.


arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = arr + 5

print(result)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [6]:
#Q37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
#     corresponding element in arr1 using NumPy broadcasting.


arr1 = np.array([[1, 2, 3]])  
arr2 = np.array([[4, 5, 6, 7],
                 [8, 9, 10, 11],
                 [12, 13, 14, 15]])  


result = arr2 * arr1.T

print(result)


[[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


In [9]:
#Q38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using 
#      NumPy broadcasting.



arr1 = np.array([1, 2, 3, 4])  
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])

result = arr2 + arr1[:, np.newaxis]

print(result)


[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [10]:
#Q39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy 
#     broadcasting.


arr1 = np.array([[1],
                 [2],
                 [3]])  

arr2 = np.array([[4, 5, 6]])  

result = arr1 + arr2

print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [13]:
#Q40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy 
#     broadcasting. Handle the shape incompatibility.


arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  

arr2 = np.array([[7, 8],
                 [9, 10]]) 

arr2_reshaped = arr2[:, np.newaxis]


result = arr1[:, :, np.newaxis] * arr2_reshaped


result_reshaped = result.reshape(2, 3, 2)

print(result_reshaped)


[[[ 7  8]
  [14 16]
  [21 24]]

 [[36 40]
  [45 50]
  [54 60]]]


In [14]:
#Q41.Calculate column wise mean for the given array:
#    arr = np.array([[1, 2, 3], [4, 5, 6]])


arr = np.array([[1, 2, 3], 
                [4, 5, 6]])


column_mean = np.mean(arr, axis=0)

print(column_mean)


[2.5 3.5 4.5]


In [16]:
#Q42. Find maximum value in each row of the given array:
#      arr = np.array([[1, 2, 3], [4, 5, 6]])



arr = np.array([[1, 2, 3], 
                [4, 5, 6]])


row_max = np.max(arr, axis=1)

print(row_max)


[3 6]


In [18]:
#Q43. For the given array, find indices of maximum value in each column.
#     arr = np.array([[1, 2, 3], [4, 5, 6]])


arr = np.array([[1, 2, 3], 
                [4, 5, 6]])


max_indices = np.argmax(arr, axis=0)

print(max_indices)



[1 1 1]


In [22]:
#Q44. For the given array, apply custom function to calculate moving sum along rows.
#          arr = np.array([[1, 2, 3], [4, 5, 6]])




def moving_sum(arr, window_size):
    
    if window_size > arr.shape[1]:
        raise ValueError("Window size must be less than or equal to the number of columns in the array")
    
    result = np.zeros((arr.shape[0], arr.shape[1] - window_size + 1), dtype=arr.dtype)
    
    for i in range(arr.shape[0]):
        for j in range(arr.shape[1] - window_size + 1):
            result[i, j] = np.sum(arr[i, j:j + window_size])
    
    return result


arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

window_size = 2
moving_sum_result = moving_sum(arr, window_size)

print(moving_sum_result)


[[ 3  5]
 [ 9 11]]


In [25]:
#Q45.In the given array, check if all elements in each column are even.

#         arr = np.array([[2, 4, 6], [3, 5, 7]])


arr = np.array([[2, 4, 6],
                [3, 5, 7]])


all_even = np.all(arr % 2 == 0, axis=0)
all_even

array([False, False, False])

In [27]:
#Q46.Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the 
#    reshaped matrix.
#     original_array = np.array([1, 2, 3, 4, 5, 6])



original_array = np.array([1, 2, 3, 4, 5, 6])


m = 2  
n = 3  


reshaped_matrix = original_array.reshape(m, n)


print(reshaped_matrix)


[[1 2 3]
 [4 5 6]]


In [29]:
#Q47.Create a function that takes a matrix as input and returns the flattened array.
#    input_matrix = np.array([[1, 2, 3], [4, 5, 6]])




def flatten_matrix(matrix):
    
    return matrix.flatten()


input_matrix = np.array([[1, 2, 3],
                         [4, 5, 6]])

flattened_array = flatten_matrix(input_matrix)


print(flattened_array)


[1 2 3 4 5 6]


In [4]:
#Q48.Write a function that concatenates two given arrays along a specified axis.
#      array1 = np.array([[1, 2], [3, 4]])
#      array2 = np.array([[5, 6], [7, 8]])




def concatenate_arrays(array1, array2, axis):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])


result = concatenate_arrays(array1, array2, axis=0)
print(result)



result = concatenate_arrays(array1, array2, axis=1)
print(result)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [5]:
#Q49. Create a function that splits an array into multiple sub-arrays along a specified axis
#     original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])




def split_array(array, indices_or_sections, axis=0):
    return np.split(array, indices_or_sections, axis=axis)


original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


sub_arrays_axis0 = split_array(original_array, 3, axis=0)
for i, sub_array in enumerate(sub_arrays_axis0):
    print(f"Sub-array {i}:\n{sub_array}\n")


sub_arrays_axis1 = split_array(original_array, 3, axis=1)
for i, sub_array in enumerate(sub_arrays_axis1):
    print(f"Sub-array {i}:\n{sub_array}\n")


Sub-array 0:
[[1 2 3]]

Sub-array 1:
[[4 5 6]]

Sub-array 2:
[[7 8 9]]

Sub-array 0:
[[1]
 [4]
 [7]]

Sub-array 1:
[[2]
 [5]
 [8]]

Sub-array 2:
[[3]
 [6]
 [9]]



In [8]:
#Q50. Write a function that inserts and then deletes elements from a given array at specified indices.
#      original_array = np.array([1, 2, 3, 4, 5])
#      indices_to_insert = [2, 4]
#      values_to_insert = [10, 11]
#      indices_to_delete = [1, 3]





def insert_and_delete_elements(array, indices_to_insert, values_to_insert, indices_to_delete):
    
    modified_array = np.insert(array, indices_to_insert, values_to_insert)
    
    
    adjusted_indices_to_delete = np.array(indices_to_delete) + np.arange(len(indices_to_delete))
    
    
    modified_array = np.delete(modified_array, adjusted_indices_to_delete)
    
    return modified_array


original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)
print(result_array)


[ 1 10  3 11  5]


In [10]:
#Q51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
#      Perform element-wise addition between `arr1` and `arr2`.


arr1 = np.random.randint(0, 10, size=10)


arr2 = np.arange(1, 11)


result = arr1 + arr2


print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise addition result:", result)


arr1: [3 5 5 4 7 7 8 0 0 6]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Element-wise addition result: [ 4  7  8  8 12 13 15  8  9 16]


In [12]:
#Q52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers 
#     from 1 to 10. Subtract `arr2` from `arr1` element-wise.


arr1 = np.arange(10, 0, -1)


arr2 = np.arange(1, 11)


result = arr1 - arr2


print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise subtraction result:", result)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Element-wise subtraction result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [13]:
#Q53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
#      Perform element-wise multiplication between `arr1` and `arr2`.



arr1 = np.random.randint(0, 10, size=5)


arr2 = np.arange(1, 6)


result = arr1 * arr2


print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise multiplication result:", result)


arr1: [0 9 8 2 6]
arr2: [1 2 3 4 5]
Element-wise multiplication result: [ 0 18 24  8 30]


In [15]:
#Q54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 
#     to 5. Perform element-wise division of `arr1` by `arr2`.


arr1 = np.arange(2, 11, 2)


arr2 = np.arange(1, 6)


result = arr1 / arr2


print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise division result:", result)


arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Element-wise division result: [2. 2. 2. 2. 2.]


In [2]:
#Q55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
#      reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.








arr1 = np.arange(1, 6)
arr2 = arr1[::-1]

result = arr1 ** arr2


print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise exponentiation result:", result)


arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Element-wise exponentiation result: [ 1 16 27 16  5]


In [6]:
#Q56.Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
#    arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])




def count_substring_occurrences(arr, substring):    
    count_func = np.vectorize(lambda x: x.count(substring))    
    return count_func(arr).sum()


arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
count = count_substring_occurrences(arr, substring)
print(count)  


3


In [8]:
#Q57. Write a function that extracts uppercase characters from a NumPy array of strings.

#       arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])





def extract_uppercase(arr):
    
    extract_func = np.vectorize(lambda x: ''.join([char for char in x if char.isupper()]))
    
    return extract_func(arr)


arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase(arr)
print(uppercase_chars)  


['H' 'W' 'OAI' 'GPT']


In [3]:
#Q58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
#     arr = np.array(['apple', 'banana', 'grape', 'pineapple'])




def replace_substring_in_array(arr, old_substring, new_substring):
    
    return np.char.replace(arr, old_substring, new_substring)


arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
new_arr = replace_substring_in_array(arr, 'apple', 'fruit')
print(new_arr)


['fruit' 'banana' 'grape' 'pinefruit']


In [6]:
#Q59. Write a function that concatenates strings in a NumPy array element-wise.
#     import numpy as np
#      arr1 = np.array(['Hello', 'World'])
#      arr2 = np.array(['Open', 'AI'])





def concatenate_arrays_elementwise(arr1, arr2):

    return np.char.add(arr1, arr2)


arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
result = concatenate_arrays_elementwise(arr1, arr2)
print(result)


['HelloOpen' 'WorldAI']


In [3]:
#Q60. Write a function that finds the length of the longest string in a NumPy array.

#         arr = np.array(['apple', 'banana', 'grape', 'pineapple'])




def longest_string_length(arr):
    
    lengths = [len(item) for item in arr]
    
    
    return max(lengths)


arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(longest_string_length(arr))  


9


In [5]:
#Q61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
#    standard deviation of the dataset using NumPy's functions.



data = np.random.randint(1, 1001, size=100)


mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Variance: {variance}")
print(f"Standard Deviation: {std_dev}")


Mean: 485.56
Median: 464.0
Variance: 96527.18639999999
Standard Deviation: 310.68824631775175


In [6]:
#Q62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the 
#      dataset.


data = np.random.uniform(1, 100, 50)


percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")


25th Percentile: 21.512448820065476
75th Percentile: 72.40326578276148


In [8]:
#Q63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
#     arrays using NumPy's `corrcoef` function.



x = np.random.rand(100)
y = np.random.rand(100)


correlation_matrix = np.corrcoef(x, y)

print("Correlation coefficient matrix:")
print(correlation_matrix)


Correlation coefficient matrix:
[[ 1.         -0.05433043]
 [-0.05433043  1.        ]]


In [10]:
#Q64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.


matrix1 = np.random.randint(1, 10, (3, 2))
matrix2 = np.random.randint(1, 10, (2, 4))


result = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)
print("\nMatrix Multiplication Result:")
print(result)


Matrix 1:
[[4 6]
 [6 6]
 [9 4]]

Matrix 2:
[[1 9 9 9]
 [5 2 3 4]]

Matrix Multiplication Result:
[[34 48 54 60]
 [36 66 72 78]
 [29 89 93 97]]


In [12]:
#Q65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
#     percentiles along with the first and third quartiles.


data = np.random.randint(10, 1001, 50)


percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)
percentile_90 = np.percentile(data, 90)


quartile_1 = np.percentile(data, 25)
quartile_3 = np.percentile(data, 75)

print(f"10th Percentile: {percentile_10}")
print(f"50th Percentile (Median): {percentile_50}")
print(f"90th Percentile: {percentile_90}")
print(f"First Quartile (25th Percentile): {quartile_1}")
print(f"Third Quartile (75th Percentile): {quartile_3}")


10th Percentile: 163.9
50th Percentile (Median): 529.5
90th Percentile: 890.8
First Quartile (25th Percentile): 318.0
Third Quartile (75th Percentile): 797.25


In [14]:
#Q66. Create a NumPy array of integers and find the index of a specific element.



arr = np.array([1, 3, 7, 9, 11, 15, 19])


element_to_find = 11
index = np.where(arr == element_to_find)[0]

print(f"Index of element {element_to_find}: {index}")


Index of element 11: [4]


In [16]:
#Q67. Generate a random NumPy array and sort it in ascending order.



random_array = np.random.randint(1, 101, 10)


sorted_array = np.sort(random_array)

print("Original array:")
print(random_array)
print("Sorted array:")
print(sorted_array)


Original array:
[85 78 26 33 13 48 94 83 61 95]
Sorted array:
[13 26 33 48 61 78 83 85 94 95]


In [18]:
#Q68. Filter elements >20  in the given NumPy array.
#     arr = np.array([12, 25, 6, 42, 8, 30])


arr = np.array([12, 25, 6, 42, 8, 30])


filtered_arr = arr[arr > 20]

print(filtered_arr)


[25 42 30]


In [20]:
#Q69. Filter elements which are divisible by 3 from a given NumPy array.
#     arr = np.array([1, 5, 8, 12, 15])


arr = np.array([1, 5, 8, 12, 15])


filtered_arr = arr[arr % 3 == 0]

print(filtered_arr)


[12 15]


In [22]:
#Q70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
#    arr = np.array([10, 20, 30, 40, 50])



arr = np.array([10, 20, 30, 40, 50])


filtered_arr = arr[(arr >= 20) & (arr <= 40)]

print(filtered_arr)


[20 30 40]


In [23]:
#Q71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
#     arr = np.array([1, 2, 3])




arr = np.array([1, 2, 3])


byte_order = arr.dtype.byteorder

print(f"Byte order of the array: {byte_order}")


Byte order of the array: =


In [26]:
#Q72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
#     arr = np.array([1, 2, 3], dtype=np.int32)




arr = np.array([1, 2, 3], dtype=np.int32)


arr.byteswap(inplace=True)

print(arr)


[16777216 33554432 50331648]


In [28]:
#Q73. For the given NumPy array, swap its byte order without modifying the original array using 
#      `newbyteorder()`.
#     arr = np.array([1, 2, 3], dtype=np.int32)



arr = np.array([1, 2, 3], dtype=np.int32)


swapped_arr = arr.newbyteorder()

print("Original array:", arr)
print("Byte-swapped array:", swapped_arr)


Original array: [1 2 3]
Byte-swapped array: [16777216 33554432 50331648]


In [31]:
#Q74. For the given NumPy array and swap its byte order conditionally based on system endianness using 
#     `newbyteorder()`.
#     arr = np.array([1, 2, 3], dtype=np.int32)



arr = np.array([1, 2, 3], dtype=np.int32)


native_endianness = '='  
current_byteorder = arr.dtype.byteorder


if current_byteorder == native_endianness:
    print("The array is already in native byte order.")
    swapped_arr = arr
else:
    print("Swapping the byte order of the array to match native endianness.")
    swapped_arr = arr.newbyteorder()

print("Original array:", arr)
print("Conditionally byte-swapped array:", swapped_arr)


The array is already in native byte order.
Original array: [1 2 3]
Conditionally byte-swapped array: [1 2 3]


In [33]:
#Q75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` 
#      attribute `byteorder`.
#      arr = np.array([1, 2, 3], dtype=np.int32)



arr = np.array([1, 2, 3], dtype=np.int32)


byte_order = arr.dtype.byteorder


if byte_order == '=':
    print("The array is in native byte order; no byte swapping is necessary.")
elif byte_order == '<':
    if np.little_endian:
        print("The array is little-endian, and the system is also little-endian; no byte swapping is necessary.")
    else:
        print("The array is little-endian, but the system is big-endian; byte swapping is necessary.")
elif byte_order == '>':
    if np.little_endian:
        print("The array is big-endian, but the system is little-endian; byte swapping is necessary.")
    else:
        print("The array is big-endian, and the system is also big-endian; no byte swapping is necessary.")


The array is in native byte order; no byte swapping is necessary.


In [34]:
#Q76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
#     an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.



arr1 = np.arange(1, 11)


copy_arr = arr1.copy()


copy_arr[0] = 100

print("Original array:", arr1)
print("Modified copy:", copy_arr)


Original array: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy: [100   2   3   4   5   6   7   8   9  10]


In [36]:
#Q77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
#      the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.




matrix = np.random.randint(1, 10, size=(3, 3))


view_slice = matrix[1:, 1:]


view_slice[0, 0] = 100

print("Original matrix:")
print(matrix)
print("Modified slice:")
print(view_slice)


Original matrix:
[[  7   3   3]
 [  4 100   1]
 [  9   2   2]]
Modified slice:
[[100   1]
 [  2   2]]


In [39]:
#Q78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
#      `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.




array_a = np.arange(1, 13).reshape((4, 3))


view_b = array_a[1:, :2]


view_b += 5

print("Original array:")
print(array_a)
print("Modified slice:")
print(view_b)


Original array:
[[ 1  2  3]
 [ 9 10  6]
 [12 13  9]
 [15 16 12]]
Modified slice:
[[ 9 10]
 [12 13]
 [15 16]]


In [41]:
#Q79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
#     `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
#     reflects changes in the original `orig_array`.


orig_array = np.arange(1, 9).reshape((2, 4))


reshaped_view = orig_array.reshape((4, 2))


reshaped_view[0, 0] = 100

print("Original array:")
print(orig_array)
print("Modified reshaped view:")
print(reshaped_view)


Original array:
[[100   2   3   4]
 [  5   6   7   8]]
Modified reshaped view:
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [43]:
#Q80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
#     elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.



data = np.random.randint(1, 10, size=(3, 4))


data_copy = data[data > 5].copy()


data_copy[0] = 100

print("Original data:")
print(data)
print("Modified copy:")
print(data_copy)


Original data:
[[2 3 3 7]
 [3 6 9 6]
 [7 1 1 4]]
Modified copy:
[100   6   9   6   7]


In [45]:
#Q81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction 
#      operations between them.



A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


addition_result = A + B
subtraction_result = A - B

print("Matrix A:")
print(A)
print("Matrix B:")
print(B)
print("Addition result:")
print(addition_result)
print("Subtraction result:")
print(subtraction_result)


Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Addition result:
[[ 6  8]
 [10 12]]
Subtraction result:
[[-4 -4]
 [-4 -4]]


In [47]:
#Q82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.





C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))


multiplication_result = np.dot(C, D)

print("Matrix C:")
print(C)
print("Matrix D:")
print(D)
print("Matrix multiplication result:")
print(multiplication_result)


Matrix C:
[[8 4]
 [9 6]
 [3 3]]
Matrix D:
[[7 6 1 7]
 [6 4 9 6]]
Matrix multiplication result:
[[80 64 44 80]
 [99 78 63 99]
 [39 30 30 39]]


In [49]:
#Q83. Create a matrix `E` and find its transpose.



E = np.random.randint(1, 10, size=(3, 4))


transpose_E = E.T

print("Matrix E:")
print(E)
print("Transpose of E:")
print(transpose_E)



Matrix E:
[[2 9 6 1]
 [2 4 2 1]
 [2 2 2 5]]
Transpose of E:
[[2 2 2]
 [9 4 2]
 [6 2 2]
 [1 1 5]]


In [50]:
#Q84. Generate a square matrix `F` and compute its determinant.



F = np.random.randint(1, 10, size=(3, 3))


det_F = np.linalg.det(F)

print("Matrix F:")
print(F)
print("Determinant of F:")
print(det_F)


Matrix F:
[[7 6 9]
 [6 7 3]
 [8 5 7]]
Determinant of F:
-103.99999999999999


In [51]:
#Q85. Create a square matrix `G` and find its inverse.


G = np.random.randint(1, 10, size=(3, 3))


inverse_G = np.linalg.inv(G)

print("Matrix G:")
print(G)
print("Inverse of G:")
print(inverse_G)


Matrix G:
[[6 2 6]
 [7 1 1]
 [6 6 1]]
Inverse of G:
[[-0.02717391  0.18478261 -0.02173913]
 [-0.00543478 -0.16304348  0.19565217]
 [ 0.19565217 -0.13043478 -0.04347826]]
